version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: appointments_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672" # For application connection
      - "15672:15672" # For web management UI
    environment:
      RABBITMQ_DEFAULT_USER: your_mq_user
      RABBITMQ_DEFAULT_PASS: your_mq_password
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
